### ISSUE TITLE
question: creating an OrderedDocument with insert without supplying a key ?

### ISSUE THREAD

**Issue by lrlna** [zonyitoo/bson-rs#105]
Hello!

I am trying to create an `OrderedDocument` from a `bson::Bson`, but it already contains keys and values, so I'd just like to be able to insert it as is without having to specify the keys. Is there a good way of doing that?

`value` is dynamic and is always of type Bson. Example:
```json
{
   "city": "Berlin",
   "street": "Oranienstraße 123",
   "postal_code": 10945
}
```
Create a document with `Document::new()` and then `.insert()` ?
```rust
let mut subdoc = Document::new();
subdoc.insert(None, value) // Edited to add 'None'
generate_schema_from_doc(subdoc)
```
or do that with `doc!` macro ?:
```rust
let mut subdoc = doc! { value };
generate_schema_from_doc(subdoc)
```
Thank you in advance!

**Comment by zonyitoo** [comment]
Hmm. I don't quite understand what you are about to do....

You are going to create an `OrderedDocument` from a `bson::Bson`, what is the actual subtype of that `bson::Bson`? `Bson::Document`?

**Comment by lrlna** [comment]
ah sorry I wasn't very clear; a bit new to rust as well so can't formulate types that well yet :O

It is a `Bson::Document`, yes. And I want to be able to create an `OrderedDocument` from it. Preferably with just the `doc!` macro. But I can't figure out if there is a way to do that without supplying the key.

**Comment by kyeah** [comment]
hi! there are a couple ways to do this, but they all involve pattern-matching the Bson enum and pulling out the inner `OrderedDocument` — if it is a Bson::Document.

To move the document out of the Bson enum (`value` cannot be used after this):
```rust
let inner_doc = match value {
  Bson::Document(doc) => doc,
   _ => panic!("test")
};
```

conditionally:
```rust
if let Bson::Document(inner_doc) = value {
  generate_schema_from_doc(inner_doc)
}
```

If you need to maintain the original Bson::Document, you can get a reference to the document:
```rust
// provided helper function from https://github.com/zonyitoo/bson-rs/blob/master/src/bson.rs#L500
// alternatively: value.as_document().expect('expected a Bson::Document');
let inner_doc_ref = value.as_document()?;
```

conditionally:
```rust
if let Bson::Document(ref inner_doc) = value {
  generate_schema_from_doc(inner_doc)
}
```

hope that makes sense!

**Comment by lrlna** [comment]
hi! thank you so much for your help! I think doing something like the pattern matching you are describing will work. I am doing something like that at another point anyways o/
