### ISSUE TITLE
Deserialize integers which don't have explicit signs to signed integers instead of unsigned integers.

### ISSUE THREAD

**Issue by magiclen** [zonyitoo/bson-rs#112]
I want to convert JSON to BSON, but I stuck on integers.

```rust
extern crate bson;
extern crate serde_json;

use bson::Document;

fn main() {
    let _doc_1: Document = serde_json::from_str("{\"a\": -1}").unwrap();

    let _doc_2: Document = serde_json::from_str("{\"a\": 1}").unwrap();
}
```

The code above panics at line 11 because bson seems to consider **1** as an unsigned integer. Is there a way to deserialize positive integers to a signed integer instead of an unsigned integer?

**Comment by zonyitoo** [comment]
You are using `serde_json`, which means that you are parsing the string in JSON's way to `Document`, which is a structure in this crate. I don't think it has anything related to BSON.

> bson seems to consider 1 as an unsigned integer

No. `serde_json` consider 1 as an unsigned integer, which is always true in JSON.

My suggestion is: You can first convert JSON to a struct, with a field `a: i32`, and then convert it back to `Document`.

**Comment by magiclen** [comment]
Thanks for you reply. But I found this way which works for me,

```rust
extern crate bson;
extern crate serde_json;

use std::io::Cursor;

use bson::Bson;
use serde_json::Value;

fn main() {
    let v: Value = serde_json::from_str("{\"a\": 1}").unwrap();

    let _doc: Bson = bson::Bson::from(v);
}
```

**Comment by zonyitoo** [comment]
Well, that is for converting a *BSON compatible JSON* to BSON.

**Comment by magiclen** [comment]
Yeah, that is what I need. Simple and easy! Thanks again.

**Comment by zonyitoo** [comment]
Close for solved.
