### ISSUE TITLE
Junk in the cargo package source

### ISSUE THREAD

**Issue by bluss** [zonyitoo/bson-rs#12]
bson 0.1.2 has a 161 MB ./db directory in its cargo package source. Consider releasing a new clean version.

This is a reminder that cargo includes all non-ignored files in your working directory when you publish — look at `git status` before you publish.

(I downloaded all crates.io crates and I started to grep for junk)

**Comment by zonyitoo** [comment]
@kyeah Is it ok to release a new version?

**Comment by bluss** [comment]
One thing I didn't realize was that the db compresses really well, the crate file is only 173 kB — so that's not so bad, but it's still extra files that will use space everywhere the crate is unpacked.

**Comment by kyeah** [comment]
Yep, let's release a new version for this.

**Comment by zonyitoo** [comment]
Ref: b1cca0eb28534fccf3aa35de908b33d3f2cfe204

**Comment by bluss** [comment]
Great!
