### ISSUE TITLE
0.13.1 should have been semver breaking release

### ISSUE THREAD

**Issue by est31** [zonyitoo/bson-rs#126]
It seems that the 0.13.1 introduced breaking changes into the API. Here is a user report in a downstream crate that got broken by the update: https://github.com/nushell/nushell/pull/530

It would be best if the 0.13.1 release could be yanked and a 0.14.0 release be done instead. Thank you!

**Comment by zonyitoo** [comment]
Ok, sorry about that.

**Comment by est31** [comment]
@zonyitoo thanks! I'd still definitely appreciate a new (semver breaking) release as it brings those crossbeam updates.

**Comment by zonyitoo** [comment]
Yes. I am adding a feature gate to optionally enable decimal128 supports.

**Comment by zonyitoo** [comment]
I have already pushed a commit: https://github.com/zonyitoo/bson-rs/commit/00edb6e47542da0e03b0ca0e592a64dc3958e33d .

Decimal128 could be enabled by `feature = "decimal128"`. Will be released with 0.14.0.

**Comment by zonyitoo** [comment]
Published v0.14.0. And I think this issue is fixed. Closing.

Again, sorry about the breaking change.
