### ISSUE TITLE
Missing encoding/decoding validity tests

### ISSUE THREAD

**Issue by kyeah** [zonyitoo/bson-rs#13]
After issues were found with the boolean and datetime encoding, it would be beneficial to add tests to ensure that all bson objects are encoded and decoded correctly, and to catch any changes that may break it.

**Comment by thijsc** [comment]
I think this test comes pretty close to achieving this goal: https://github.com/zonyitoo/bson-rs/blob/master/tests/modules/ordered.rs#L41

**Comment by matsimitsu** [comment]
:+1:

**Comment by kyeah** [comment]
I think I'll actually close this, even though the above tests are missing a few types. For reference:

* RegExp(String, String)
* JavaScriptCode(String)
* JavaScriptCodeWithScope(String, Document)
* Binary(BinarySubtype, Vec)

:+1:
