### ISSUE TITLE
-rs isn't conventional in crate names

### ISSUE THREAD

**Issue by steveklabnik** [zonyitoo/bson-rs#2]
Every crate is a Rust crate, so this should be named `bson`. It's also available on crates.io.

**Comment by zonyitoo** [comment]
Hmm, I think you're right. It is an old name convention. Let me fix it.

**Comment by zonyitoo** [comment]
Please check this out: https://crates.io/crates/bson

**Comment by steveklabnik** [comment]
:confetti_ball:
