### ISSUE TITLE
Add rustc-serialize/serde Encoder/Decoder implementation

### ISSUE THREAD

**Issue by netvl** [zonyitoo/bson-rs#29]
It would be nice to have a suitable Encoder/Decoder (or Serializer/Deserializer) implementation for `Bson` type in order to automatically serialize serializable types to BSON.

**Comment by zonyitoo** [comment]
Sounds promising. But I don't have time to implement it recently, so I should mark it as "enhancement".

BTW, I am happy to receive a PR. :P
