### ISSUE TITLE
module `ordered` is private

### ISSUE THREAD

**Issue by kimhyunkang** [zonyitoo/bson-rs#33]
Is there a specific reason `ordered` module is private?

This makes convenient macros such as `try!` unusable.

For example:

```rust
use bson::Document;

fn set_and_get_age() -> Result<i32, MyCustomError> {
  let mut doc = Document::new();
  doc.insert("age".to_string(), 32 as i32);

  let value = try!(doc.get_i32("age"));
  Ok(value)
}
```

This code does not compile because `MyCustomError` does not implement `From<bson::ordered::ValueAccessError>`. You can't provide a custom impl for From, because the module is private.

**Comment by zonyitoo** [comment]
Because the `ordered` is just a temporary solution for implementing ordered map. I am still waiting for the `linked-hash-map` to be stablized.

**Comment by zonyitoo** [comment]
Merge with #35 .
