### ISSUE TITLE
Use linked-hash-map to implement OrderedDocument

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/bson-rs#35]
The `ordered::OrderedDocument` is a temporary solution while the `linked-hash-map` crate can only be compiled with nightly. But now, [linked-hash-map](https://github.com/contain-rs/linked-hash-map) can be compiled with the latest stable rustc v1.7 (https://github.com/contain-rs/linked-hash-map/issues/28).

So I suggest that we could migrate it to `linked-hash-map`.

**Comment by dariusc93** [comment]
How would this impact current use of bson?

**Comment by zonyitoo** [comment]
Currently the `OrderedDocument` is implemented as `Vec` + `BTreeMap` pair to maintain insertion order. Which means that we need to do a `O(n)` search on the `Vec` and store the `String` key twice.
