### ISSUE TITLE
Crate release supporting serde 0.8

### ISSUE THREAD

**Issue by kali** [zonyitoo/bson-rs#40]
Hey!

Thanks for your great work on this crate. Could we get a release for the changes you made for serde 0.8 ?

Thanks :)

**Comment by zonyitoo** [comment]
Will upload until @kyeah solves #38

**Comment by kali** [comment]
ho, all right, thanks.

**Comment by zonyitoo** [comment]
Already uploaded with version `v0.3.0`.
