### ISSUE TITLE
[Feature Request] Support BSON Symbols

### ISSUE THREAD

**Issue by alanhdu** [zonyitoo/bson-rs#43]
Although the BSON spec says that symbols (which start with `\x0E`) are deprecated, Mongo itself will happily encode and store symbols. Unfortunately, that means `bson-rs` should also support symbols.

**Comment by zonyitoo** [comment]
Hmm, why would you need this feature that is already deprecated? In the spec, symbols is defined as

```
"\x0E" e_name string	Deprecated
```

which looks exactly the same as

```
"\x02" e_name string	UTF-8 string
```

**Comment by alanhdu** [comment]
Well, we need because Mongo's ruby driver will store `:hello` as a symbol in Mongo without warnings or errors, and we'd like to read that data out w/ `bson-rs`.

I mean, I don't know why Symbols were even in the spec in the first place (and frankly, they're not very well supported by Mongo itself, either). The best case scenario would be for Mongo to officially deprecate symbols (including _all_ its drivers), but even then we'd need this for legacy applications.

**Comment by zonyitoo** [comment]
Reasonable. I will support this later today.

**Comment by alanhdu** [comment]
Awesome. Thanks!

**Comment by zonyitoo** [comment]
Please help me to test this commit. :)
