### ISSUE TITLE
Update to serde 0.9

### ISSUE THREAD

**Issue by dtolnay** [zonyitoo/bson-rs#49]
Check out the release notes here: https://github.com/serde-rs/serde/releases/tag/v0.9.0

**Comment by zonyitoo** [comment]
Spent a morning trying to modify all the existing code for 0.9, what a pain!

**Comment by dtolnay** [comment]
Are you planning to drop rustc-serialize support as part of this update now that serde derives are stable? Rustc-serialize has been deprecated for a long time and the toml and bincode crates are dropping it as part of the serde 0.9 update.

**Comment by zonyitoo** [comment]
I don't have plan for this now. This can be discussed in the other issue.

**Comment by dtolnay** [comment]
Makes sense. I filed #51 to follow up.

**Comment by zonyitoo** [comment]
@kyeah You may also want to take a look at this. If the last commit is Ok, I will merge it to master.

**Comment by kyeah** [comment]
@zonyitoo just looked through it; two minor comments, but looks good otherwise. Thanks for updating all those dependencies!

**Comment by zonyitoo** [comment]
Already updated. I will merge this if it is Ok.

**Comment by kyeah** [comment]
looks good 👍

**Comment by zonyitoo** [comment]
Already published as v0.4
