### ISSUE TITLE
Remove rustc-serialize support

### ISSUE THREAD

**Issue by dtolnay** [zonyitoo/bson-rs#51]
Now that custom derives are stable, rustc-serialize is deprecated in favor of serde. Rustc-serialize has not been actively developed for a long time, which means if anyone needs rustc-serialize support for some reason they can always use an old version of the bson crate - no need for us to keep the code around. Cleaning this up would remove a stumbling block for new users trying to use this crate with modern Rust.

**Comment by zonyitoo** [comment]
cc @kyeah

**Comment by kyeah** [comment]
Thanks for the issue @dtolnay! I'll get on this over the weekend.

**Comment by zonyitoo** [comment]
PR is already merged. Close.
