### ISSUE TITLE
Bugs in decoder found by fuzzing

### ISSUE THREAD

**Issue by killercup** [zonyitoo/bson-rs#64]
Found the following:

- [ ] "thread '<unnamed>' panicked at 'No such local time'"
    From: `chrono-0.2.25/src/offset/mod.rs:151` via `src/decoder/mod.rs:172`
- [ ] "thread '<unnamed>' panicked at 'attempt to multiply with overflow'" - `src/decoder/mod.rs:172`
- [ ] "thread '<unnamed>' panicked at 'attempt to subtract with overflow'" `src/decoder/mod.rs:45`
- [ ] "AddressSanitizer failed to allocate 0xffffffff93000000 bytes" (whatever that means in real life)

Full logs: https://gist.github.com/killercup/5e8623e0d8b0fe9868b45eb223ef51d8 (See last few lines for inputs used, in bytes or base64)

See <https://github.com/rust-fuzz/targets/pull/51> for sources, I ran it with

```sh
$ env ASAN_OPTIONS="detect_odr_violation=0 allocator_may_return_null=1" ./run-fuzzer.sh bson read_bson
```

cc https://github.com/rust-fuzz/targets/issues/39

**Comment by kyeah** [comment]
nice, thanks 🙇 

Gonna use this as a tracking issue instead of splitting this out since this seems like a nice concise set.


    

- [ ] "thread panicked at 'No such local time'" 
  From: chrono-0.2.25/src/offset/mod.rs:151 via src/decoder/mod.rs:172
- [ ] "thread '' panicked at 'attempt to multiply with overflow'" - src/decoder/mod.rs:172
- [ ] "thread '' panicked at 'attempt to subtract with overflow'" src/decoder/mod.rs:45
- [ ] "AddressSanitizer failed to allocate 0xffffffff93000000 bytes" (whatever that means in real life)

**Comment by zonyitoo** [comment]
@neosilky Is this what you are expected? :)

**Comment by neosilky** [comment]
@zonyitoo Yes - nice job!

So I'm still hitting the `attempt to subtract with overflow` panic in `src/decoder/mod:50` and I'm getting two `fatal runtime error: memory allocation failed` errors, which are weird.

**Comment by zonyitoo** [comment]
```
attempt to subtract with overflow
```

That's weird... `src/decoder/mod:50` is `read_string`, which is a UTF-8 string in BSON. In BSON's spec, UTF-8 String must be ended with `\x00`, which means that the length of string must be `>= 1`.

> string	::=	int32 (byte*) "\x00"	String - The int32 is the number bytes in the (byte*) + 1 (for the trailing '\x00'). The (byte*) is zero or more UTF-8 encoded characters.

What should I do for length = 0? ... Hmmm....

Can you dump the original binary data?

**Comment by zonyitoo** [comment]
It seems that the Go's implementation will also crash in this case: https://github.com/go-mgo/mgo/blob/v2/bson/decode.go#L771-L772 .

**Comment by zonyitoo** [comment]
It won't panic now. But return an DecoderError.

**Comment by neosilky** [comment]
@zonyitoo Nice one, it looks like you've done a sane thing :grinning: 

I'm still getting some weird memory issues, I'll see if I can get further with them.

**Comment by zonyitoo** [comment]
Ahh.. the `nsecs` overflows `u32` ...

**Comment by saghm** [comment]
@zonyitoo note that mgo is neither an official MongoDB driver or actively maintained; the official (albeit pre-stable) driver is [here](https://github.com/mongodb/mongo-go-driver)

**Comment by zonyitoo** [comment]
@neosilky This commit should fix the issue.

**Comment by zonyitoo** [comment]
Wait a minute... `((time % 1000) as u32) * 1_000_000` won't overflows `u32` ... 

```
999 * 1_000_000 < u32::max_value() aka 4294967296
```

**Comment by zonyitoo** [comment]
Ah my fault.... the `time` variable is a `i64`, which means that it may be `< 0`.

**Comment by zonyitoo** [comment]
Fixed. And close.

**Comment by neosilky** [comment]
Thanks!

**Comment by kyeah** [comment]
Great investigations, thanks @zonyitoo!
