### ISSUE TITLE
how to deserialize or serialize a DateTime<UTC>?

### ISSUE THREAD

**Issue by daltonxiong** [zonyitoo/bson-rs#65]
I can't work with https://serde.rs/custom-date-format.html.

**Comment by zonyitoo** [comment]
cc @kyeah

**Comment by Matrix-Zhang** [comment]
here is my test code:
```
mod my_date_format {
    use bson::Bson;
    use chrono::datetime::DateTime;
    use chrono::offset::utc::UTC;
    use serde::{self, Deserialize, Serializer, Deserializer};
    use serde::ser::SerializeTupleStruct;

    pub fn serialize<S>(date: &DateTime<UTC>, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        let mut ts = serializer.serialize_tuple_struct("_", 0)?;
        ts.serialize_field(&Bson::UtcDatetime(date.clone()))?;
        ts.end()
    }
}

#[derive(Debug, Serialize)]
pub struct Account {
    #[serde(with = "my_date_format")]
    create_datetime: DateTime<UTC>,
}

#[test]
fn test_serialize {
    let account = Account { create_datetime: UTC::now() };
    let result = to_bson(&account).unwrap();
    println!("result - 0: {:?}", result);
    let result = bson!({"create_datetime" => (UTC::now())});
    println!("result - 1: {:?}", result);
}

```
the output is:
```
result - 0: Document({ create_datetime: [Date("2017-04-26 02:18:22.692 UTC")] })
result - 1: Document({ create_datetime: Date("2017-04-26 02:18:22.692840135 UTC") })
```
it's strange, i check the bson source, found the encoder's serde.rs about the Tuple and TupleStruct etc have a array inner ? any special reason for that ?

**Comment by daltonxiong** [comment]
my test code

`    #[derive(Serialize, Deserialize, Debug)]
    pub struct Test{
        #[serde(rename = "_id")]
        id: String,
        create_time: bson::Bson,
    }


    let foo = Test{
        id: "1234".to_string(),
        create_time: bson::Bson::UtcDatetime(UTC::now()),
    };

    let ser_foo = bson::to_bson(&foo).unwrap();
    println!("ser_foo: {:?}", ser_foo);

    let de_foo: Test = bson::from_bson(ser_foo).unwrap();
    println!("de_foo: {:?}", de_foo);`

**Comment by daltonxiong** [comment]
`    #[derive(Serialize, Deserialize, Debug)]
    pub struct Test{
        #[serde(rename = "_id")]
        id: String,
        create_time: bson::Bson,
    }


    let foo = Test{
        id: "1234".to_string(),
        create_time: bson::Bson::UtcDatetime(UTC::now()),
    };

    let ser_foo = bson::to_bson(&foo).unwrap();
    println!("ser_foo: {:?}", ser_foo);

    let de_foo: Test = bson::from_bson(ser_foo).unwrap();
    println!("de_foo: {:?}", de_foo);`

**Comment by daltonxiong** [comment]
my test code

'''
    #[derive(Serialize, Deserialize, Debug)]
    pub struct Test{
        #[serde(rename = "_id")]
        id: String,
        create_time: bson::Bson,
    }


    let foo = Test{
        id: "1234".to_string(),
        create_time: bson::Bson::UtcDatetime(UTC::now()),
    };

    let ser_foo = bson::to_bson(&foo).unwrap();
    println!("ser_foo: {:?}", ser_foo);

    let de_foo: Test = bson::from_bson(ser_foo).unwrap();
    println!("de_foo: {:?}", de_foo);
'''

**Comment by daltonxiong** [comment]
my test code

```
    #[derive(Serialize, Deserialize, Debug)]
    pub struct Test{
        #[serde(rename = "_id")]
        id: String,
        create_time: bson::Bson,
    }

    let foo = Test{
        id: "1234".to_string(),
        create_time: bson::Bson::UtcDatetime(UTC::now()),
    };

    let ser_foo = bson::to_bson(&foo).unwrap();
    println!("ser_foo: {:?}", ser_foo);

    let de_foo: Test = bson::from_bson(ser_foo).unwrap();
    println!("de_foo: {:?}", de_foo);
```

and outout is

```
ser_foo: Document({ _id: "1234", create_time: Date("2017-04-27 07:38:55.810 UTC") })
de_foo: Test { id: "1234", create_time: UtcDatetime(2017-04-27T07:38:55.810Z) }
```

the chrono last version is 0.3, but bson-rs use 0.2

**Comment by Matrix-Zhang** [comment]
Bson is impl se and de, so it's ok, but the chrono's datetime just se and de with string not bson's extend json format

**Comment by Gedweb** [comment]
> ```
> pub struct Test{
>     #[serde(rename = "_id")]
>     id: String,
>     create_time: bson::Bson,
> }
> ```

Here `Test` a typical model. And model must don't know anything about a date type use with them.

**Comment by zonyitoo** [comment]
It is quite hard to support `DateTime` directly to `Bson`'s extended format.

One possible solution is to create a wrapper type, `BsonDateTime`

```rust
struct BsonDateTime(pub DateTime<UTC>);

impl Serialize for BsonDateTime
impl Deserialize for BsonDateTime
```

and then you can use `BsonDateTime` directly in struct

```rust
#[derive(Serialize, Deserialize)]
pub struct Foo {
    date_time: BsonDateTime,
}
```

**Comment by Matrix-Zhang** [comment]
@zonyitoo could you anwser my question? why the inner is array? 
i

**Comment by zonyitoo** [comment]
Because you serialize it with `serializer.serialize_tuple_struct("_", 0)`

**Comment by Matrix-Zhang** [comment]
of cause i know the serialize_tuple_struct, i meas why in the serialize_tuple_struct use array?
i think if someone need array may be use Bson::Array to serialize

**Comment by zonyitoo** [comment]
because `serialize_tuple_struct` will eventually produce an Array. You shouldn't call this function if you don't expect this behavior.

**Comment by Matrix-Zhang** [comment]
@daltonxiong 
```
#[macro_use]
extern crate bson;
extern crate chrono;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use bson::to_bson;
use chrono::datetime::DateTime;
use chrono::offset::utc::UTC;

mod my_date_format {
    use bson::Bson;
    use serde::ser::Serialize;
    use serde::Serializer;
    use chrono::datetime::DateTime;
    use chrono::offset::utc::UTC;

    pub fn serialize<S>(datetime: &DateTime<UTC>, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        let bson = Bson::UtcDatetime(datetime.to_owned());
        bson.serialize(serializer)
    }
}

#[derive(Debug, Serialize)]
pub struct Account {
    #[serde(with = "my_date_format")]
    create_datetime: DateTime<UTC>,
}

fn main() {
    let account = Account { create_datetime: UTC::now() };
    let result = to_bson(&account).unwrap();
    println!("result - 0: {:?}", result);
    let result = bson!({"create_datetime" => (UTC::now())});
    println!("result - 1: {:?}", result);
}
```
it works well....

**Comment by Matrix-Zhang** [comment]
the deserialize:
```
        pub fn deserialize<'de, D>(deserializer: D) -> Result<DateTime<UTC>, D::Error>
            where D: Deserializer<'de>
        {
            match Bson::deserialize(deserializer)? {
                Bson::UtcDatetime(datetime) => Ok(datetime),
                _ => Err(Error::Custom("Only Support chrono's DateTime<UTC>.")),
            }
        }
```

**Comment by zonyitoo** [comment]
Please check the latest commit, it would be more convenient to serialize your struct with `bson::UtcDateTime`

```rust
use bson::UtcDateTime;

#[derive(Serialize, Deserialize)]
struct Foo {
    date_time: UtcDateTime,
}

let foo = Foo { date_time: From::from(UTC::now()) };
let ser_bson = bson::to_bson(&foo)?;
let de_foo: Foo = bson::from_bson(ser_bson)?;
```

**Comment by c0va23** [comment]
@zonyitoo, when you plan to release version 0.7.1 with this fix?

**Comment by zonyitoo** [comment]
No one have gave me any responses about this ... Ok, I will release it now. cc @kyeah , maybe you would want to upgrade the mongodb driver.

BTW, @kyeah , mongodb's driver should simply deps `bson` to `0.7`

**Comment by c0va23** [comment]
@zonyitoo, thank you!
