### ISSUE TITLE
json::Value into Bson failed when value is Float

### ISSUE THREAD

**Issue by Matrix-Zhang** [zonyitoo/bson-rs#66]
see bson.rs: 270

**Comment by zonyitoo** [comment]
Please @Matrix-Zhang check the lastest commit. cc @kyeah

**Comment by kyeah** [comment]
@zonyitoo can you publish 0.6.1 when you get the chance? thanks!

**Comment by zonyitoo** [comment]
Sure. Will be published tonight. (+0800)

**Comment by zonyitoo** [comment]
@kyeah already published.

**Comment by kyeah** [comment]
:+1:
