### ISSUE TITLE
from_bson failed when sub document's field have i32

### ISSUE THREAD

**Issue by Matrix-Zhang** [zonyitoo/bson-rs#69]
from_bson failed when some field is i32

**Comment by zonyitoo** [comment]
Please provide a reproducible test case.

**Comment by Matrix-Zhang** [comment]
```
#[macro_use]
extern crate bson;
extern crate serde;
#[macro_use]
extern crate serde_derive;

use bson::{Bson, from_bson};

#[derive(Debug, Deserialize, Serialize)]
struct Bar {
    inner: i32,
}

#[derive(Debug, Deserialize, Serialize)]
struct Foo {
    bar: Vec<i32>,
}

fn main() {
    let bar = doc! {
        "inner" => 1
    };

    let foo = doc! {
        "bar" => (Bson::Array(vec![Bson::Document(bar)]))
    };

    let bson = Bson::from(foo);

    let foo = from_bson::<Foo>(bson).unwrap();

    println!("{:?}", foo);
}
```

**Comment by saghm** [comment]
I'm pretty sure that's working as designed; the document `{ "inner" => 1 }` isn't able to be converted to an integer because it's a document, not an integer. If you instead use  `vec![Bson::I32(1)]`, it works fine.

**Comment by saghm** [comment]
Oh, I see, you're trying to get it to deserialize into a Bar and then the bar into a Foo. Given that your `from_bson` call is only referencing the type Foo, I'm guessing that the only way this *might* be possible is by implementing `From<Bar` for Foo. I'm not sure if this will be able to happen in the call to `from_bson`, though.

**Comment by zonyitoo** [comment]
I am pretty sure this is not a bug.

```rust
let foo = doc! {
    "bar" => (Bson::Array(vec![Bson::Document(bar)]))
};
```

What you wanted to do is to deserialize a struct `Foo2`, which has a `bar` field of type `Vec<Bar>`:

```rust
#[derive(Debug, Deserialize, Serialize)]
struct Foo2 {
    bar: Vec<Bar>,
}

let foo = from_bson::<Foo2>(bson).unwrap();
```

So if you want to deserialize something into `Foo`, you should construct your bson value like:

```rust
let doc = doc! {
    "bar" => (Bson::Array(vec![Bson::I32(1)]))
};
// NOTE that the Bson::Array(vec![Bson::I32(1)]) could be deserialized to `Vec<i32>` as you
// expected.
```

**Comment by Matrix-Zhang** [comment]
it just a sample, the data actually stroe in mongodb,

i pick it up from db ,and want to deserialize to my struct? if change i32 to String is OK

**Comment by zonyitoo** [comment]
Base on your example, it is pretty clear that you have to write `Vec<Bar>` instead of `Vec<i32>`.
