### ISSUE TITLE
InvalidMapKeyType when encode HashMap to bson

### ISSUE THREAD

**Issue by YjyJeff** [zonyitoo/bson-rs#73]
Hi, I want to encode a HashMap to bson so that I can store it in MongoDB. My HashMap type is `HashMap<u64, usize>`. When I ran the code, it panic and told me that InvalidMapKeyType(FloatingPoint(....)). Can't I use this method to encode HashMap in such type?
Thanks in advance!

**Comment by zonyitoo** [comment]
1. BSON does not support unsigned integer type. So please at least change it to `i64`.
2. Please provide a reproducible example .

**Comment by YjyJeff** [comment]
Naive code: 
`extern crate bson;
use std::collections::HashMap;
fn main() {
    let mut map: HashMap<i64, i64> = HashMap::new();
    map.insert(1, 0);
    map.insert(2, 1);
    let tmp = bson::to_bson(&map).unwrap();
}
`
When run this code, it said that `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidMapKeyType(I64(2))', ../src/libcore/result.rs:837`

**Comment by zonyitoo** [comment]
Well, please refer to the specification. BSON's Object type only supports `String` as key.

http://bsonspec.org/spec.html

**Comment by YjyJeff** [comment]
Thanks, It actually helps!
