### ISSUE TITLE
doc! "cannot find macro 'doc!' in this scope"

### ISSUE THREAD

**Issue by greenpdx** [zonyitoo/bson-rs#78]
I am getting the error "cannot find macro 'doc!' in this scope". I have added the extern crate

     #[use_macro(bson, doc)]
     extern crate bson;

     use bson::{Bson, Document, encode_document, decode_document};

    fn get_user_email(self: &Self, email: Value) {
        let coll = self.mongo.db("tnv").collection("person");
        let doc = doc! { "email" => email };
        let cursor = coll.find(doc, None);
        println!("{:?}", cursor );
    }

    error: cannot find macro `doc!` in this scope
      --> src/main.rs:92:19
       |
  92 |         let doc = doc! { "email" => email };
       |                        ^^^

error: aborting due to previous error(s)

I know this is probably something I am doing, but I am lost for a fix.

[main.txt](https://github.com/zonyitoo/bson-rs/files/1237212/main.txt)

**Comment by kyeah** [comment]
Hey @greenpdx! This might just be due to the macro import statement being `use_macro` instead of `macro_use`. The compiler should error on unknown processors though.

I also ran into a couple of other compiler errors on the latest stable rust version — what version are you running on?

**Comment by greenpdx** [comment]
Thanks.

rustc --version
rustc 1.19.0 (0ade33941 2017-07-17)

I am just learning rust, so I am breaking many things
