### ISSUE TITLE
I can't run the code in the example well

### ISSUE THREAD

**Issue by zuijiaoluo** [zonyitoo/bson-rs#92]
```
let mongoCollection = client.db("test").collection("movies");
  let person = Person {
    id: "12345",
    name: "Emma",
    age: 3,
  };

  let serialized_person = bson::to_bson(&person)?; // Serialize

  if let bson::Bson::Document(document) = serialized_person {
    mongoCollection.insert_one(document, None)?; // Insert into a MongoDB collection
  } else {
    println!("Error converting the BSON object into a MongoDB document");
  }
```
![image](https://user-images.githubusercontent.com/22735208/41268399-72214344-6e32-11e8-86d3-3ac1b14f19cb.png)
![image](https://user-images.githubusercontent.com/22735208/41268411-7ebba7de-6e32-11e8-9a34-0bee71fbc737.png)

**Comment by zonyitoo** [comment]
```
cannot use the `?` operator in a function that returns `()`
```

Please look deep into the `?` operator for more detail. For quick solve, you can let your function return `EncoderResult<()>`

**Comment by zonyitoo** [comment]
Close. Because this issue is not a BSON-rs's bug.

**Comment by JJBordy** [comment]
Wouldn't the correct example now be ?

```
 let person = Person {
        id: bson::oid::ObjectId::new().unwrap(),
        name: String::from("Emma"),
        age: 3,
    };
```

If someone reads this: is there a way to let the ObjectID to be generated automatically?
As I understood, an ObjectID is guaranteed to be unique if it is generated in the database (for the specific database/collection);
We can't allow null fields, so we are forced to generate an ObjectID inside the application (for new objects);
