### ISSUE TITLE
Creating an Array of ObjectID for MongoDB Aggregation

### ISSUE THREAD

**Issue by nevi-me** [zonyitoo/bson-rs#96]
I'm cross-posting this here from [https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/262](https://github.com/mongodb-labs/mongo-rust-driver-prototype/issues/262) in case it's more a BSON issue

___ 

I'm trying to convert a service from Java/Kotlin to Rust, but I'm having issues with some "complex" aggregation steps.

I've been unable to find how to do it on both this repo and the `bson-rs` repo. Can someone help me?

How can I translate something like the below into a Rust aggregation stage?

```js
const aggregationStages = [{
  "$match": {
    "_id": {
      "$in": [ObjectId("5b4289600000000000000000"), ObjectId("5b1afc600000000000000000")]
    }
  },
  "$project": {
    "_id": 1,
    "field": 1,
    "hours": [
      {
        "starts": {
          "$arrayElemAt": ["$times.start", 0]
        }
      }, 
      {
        "ends": {
          "$arrayElemAt": ["$times.end", -1]
        }
      }
    ]
  }
}]
```

I suppose I don't know how to convert arrays into valid Bson documents.

I tried the following, but have `<bson macros>` errors.

```rust
// get the colelction from the db
let coll = client.db("mydb").collection("places");
let mut aggregation_stages: Vec<bson::Document> = vec![];
let mut aggregation_options = mongodb::coll::options::AggregateOptions::new();
aggregation_options.allow_disk_use = Some(true);
aggregation_options.batch_size = 1000;

let object_ids = ["5b4289600000000000000000", "5b1afc600000000000000000"];
let mut ids: Vec<bson::oid::ObjectId> = vec![];

  for x in object_ids.iter() {
    ids.push(bson::oid::ObjectId::with_string(x).unwrap())
  }

    aggregation_stages.push(doc! { "$match": doc! { "_id": doc! { "$in": ids} }});aggregation_stages.push(doc! {"$project": doc! {
  "_id" : 1,
  "other_field" : 1,
  "hours": [
    doc! { "starts" : doc! {"$arrayElemAt" : ["$times.start", 0]} },
    doc! { "ends" : doc! {"$arrayElemAt" : ["$times.end", -1]} }
  ]
}});
```

I'm getting the below error:

```
error[E0277]: the trait bound `bson::Bson: std::convert::From<std::vec::Vec<bson::oid::ObjectId>>` is not satisfied
   --> src\main.rs:111:60
    |
111 |     aggregation_stages.push(doc! { "$match": doc! { "_id": doc! { "$in": ids} }});
    |                                                            ^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<std::vec::Vec<bson::oid::ObjectId>>` is not implemented for `bson::Bson`
    |
    = help: the following implementations were found:
              <bson::Bson as std::convert::From<i32>>
              <bson::Bson as std::convert::From<f32>>
              <bson::Bson as std::convert::From<std::vec::Vec<bson::Bson>>>
              <bson::Bson as std::convert::From<(bson::spec::BinarySubtype, std::vec::Vec<u8>)>>
            and 16 others
    = note: required by `std::convert::From::from`
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

```

**Comment by saghm** [comment]
Hi @nevi-me! The issue here is that the `Bson::Array` expects a `Vec<Bson>`, and in this case you've provided a `Vec<ObjectId>`. If you wrap each ObjectId in `Bson::ObjectId`, this will work:

```
use bson::Bson;
use bson::oid::ObjectId;

// Note that you don't actually need to declare the type here; it will be inferred properly.
let mut ids= vec![];

for x in object_ids.iter() {
    ids.push(Bson::ObjectId(ObjectId::with_string(x).unwrap()));
}
```

For some extra fun, here's how you could do it using iterators instead of a for loop:

```
use bson::Bson;
use bson::oid::ObjectId;

let ids: Vec<_> = ["5b4289600000000000000000", "5b1afc600000000000000000"]
    .into_iter()
    .map(|oid_string| Bson::ObjectId(
        ObjectId::with_string(oid_string).unwrap()))
    .collect();
```

**Comment by nevi-me** [comment]
Thanks @saghm! Do you mind if I keep this issue open for a bit longer? I'm converting a long pipeline from the Java API, and it's using quite a lot of aggregation features, so I might still get stuck with other computer issues that I can't resolve myself.

**Comment by saghm** [comment]
If you run into different issues, it's probably better to use separate issues; that way, other users who run into the same problem in the future can search for them more easily (and find the responses without having to scroll through a bunch of unrelated things). If you end up filing a bunch of issues, that's totally file; think of it as saving time for other users in the future by categorizing them.

**Comment by nevi-me** [comment]
Thanks! I know some library maintainers prefer questions that might not be bugs asked on S/O. So I'm often unsure of how to strike a balance.
